# Generated by Django 4.0.2 on 2022-04-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=32, verbose_name='Apellido')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('height', models.FloatField(default=0.0, verbose_name='Altura')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'db_table': 'persons',
                'ordering': ['id', '-age'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre trabajo')),
                ('status', models.BooleanField(default=True, verbose_name=' Estatus')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app1.person', verbose_name='Persona')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Correo')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Avatar')),
                ('address', models.CharField(max_length=512, verbose_name='dirección')),
                ('status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
    ]
